version: '3.8'

services:
  backend-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend_api_service
    ports:
      - "8001:8001"
    env_file:
      - Backend/.env
    environment:
      - QDRANT_HOST=${QDRANT_HOST:-172.178.38.117}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - METADATA_PATH=${METADATA_PATH:-/app/data/qdrant_db_metadata.json}
      - API_BASE_URL=${API_BASE_URL:-http://0.0.0.0:8001}
      - CHAT_API_BASE_URL=${CHAT_API_BASE_URL:-http://172.178.38.117:8001}
      - PROMPT_FILE_PATH=/app/data/prompt.txt
    volumes:
      - ./Backend:/app
      - ./logs:/app/logs
    restart: unless-stopped

  frontend-app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_app_service
    ports:
      - "8601:8601"
    environment:
      - QDRANT_HOST=${QDRANT_HOST:-172.178.38.117}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - METADATA_PATH=${METADATA_PATH:-/app/data/qdrant_db_metadata.json}
      - CACHE_TTL=${CACHE_TTL:-300}
      - STREAMLIT_SERVER_PORT=8601
      - BACKEND_API_BASE_URL=http://backend-api:8001
      - CHAT_API_BASE_URL=${CHAT_API_BASE_URL:-http://172.178.38.117:8001}
    volumes:
      - ./Frontend/src:/app/src
      - ./Frontend/data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - backend-api

volumes:
    qdrant_storage:
    ollama_data:

# Optional Qdrant/Ollama services (uncomment and adjust if needed)
#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: qdrant_service
#     ports: ["6333:6333", "6334:6334"]
#     volumes: [ "qdrant_storage:/qdrant/storage" ]
#     restart: unless-stopped

#   ollama:
#     image: ollama/ollama:latest
#     container_name: ollama_service
#     ports: [ "11434:11434" ]
#     volumes: [ "ollama_data:/root/.ollama" ]
#     restart: unless-stopped
#     # GPU config...